### ISSUE TITLE
I dont understand how use this

### ISSUE THREAD

**Issue by estvmachine** [the86freak/Splashscreen-Clipboard#1]
Sorry can you precise how i can use this plugin?. Im really like use it.

**Comment by the86freak** [comment]
in general it works like this:
you put/compile the exe into the same folder as nw.exe.
but you start the splashScreen_Clipboard.exe.
The splash-screen.exe itself displayes reads what's in the clipboard and displays that.
With this method you can tell the splashscreen how much of the app you wanted to start, has already been loaded.

Steps:
1. Download the https://github.com/the86freak/Splashscreen-Clipboard/blob/master/Release/SplashScreen_Clipboard.exe
2. copy it to the folder of your nw.exe
modify your app:
3. add the JS-File https://github.com/the86freak/Splashscreen-Clipboard/blob/master/JS/splashInfo.js
to your app
4. during startup of your app, add some clipboar-infos with: 
splashInfo.set('Message you want to show above the progress bar', 10, [waitTime/Timeout]);
where '10' is an example of the total progress. The timeout is optional - more for testing purposes. So after the process which was following after that, you can send the next command.

example:

``` JS
{
...
splashInfo.set('start method...', 10);
someStartupMethod1();
splashInfo.set('start longer method loading ...', 40);
someLongerMethod();
splashInfo.set('start reeeally long method ...', 95);
someReallyLongMethod();
//after that method everything should be loaded.
splashInfo.set('Loading finished', 100);
}
```

**Comment by estvmachine** [comment]
My package.json open a index.html, for use this i need to start in a javascript file doesnt?

**Comment by the86freak** [comment]
you can still link to your index.html but yeah, you have to call some JS then.
How this is done after building the DOM, choose of those options here:
http://stackoverflow.com/questions/9899372/pure-javascript-equivalent-to-jquerys-ready-how-to-call-a-function-when-the

I like jQuery, but go with the plain for testing: just add this into your body:

``` HTML
<html>
<head>
</head>
<body>
Your HTML here

<script>
// self executing function here
(function() {
   // your page initialization code here
   // the DOM will be available here

})();
</script>
</body>
</html>
```

(from SO)
